title: TaylorZ's Notes
author: talyorz
subtitle: always young, always coding.

url: "https://zhumiao-taylor.github.io"
baseurl: "/note"

footer_only_homepage: true
footer_url: "https://github.com/zhumiao-taylor"
footer_text: "Written by talyorz"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://zhumiao-taylor.github.io"

theme: jekyll-theme-merlot